# Auction Application Database
# Create as AuctionDB
# User name: oracle
# Password: welcome1
#

# Drop existing tables and Constraints
#

DROP TABLE Tags;
DROP TABLE WatchedAuctions;
DROP TABLE Bid;
DROP TABLE Auction;
DROP TABLE AutoItem;
DROP TABLE Item;
DROP TABLE Image;
DROP TABLE AuctionUser;


# Create tables
#

# Tags Table adde in lesson
#

CREATE TABLE Tags (
    ItemID INTEGER NOT NULL,
    Keywords VARCHAR(20) NOT NULL
);

# Image holds one or more photos for an item
# Note that ImageID is always autogenerated

CREATE TABLE Image (
                ImageID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
                Content BLOB NOT NULL,
                ContentType VARCHAR(20) NOT NULL,
                PRIMARY KEY (ImageID)
);


# Item is what is for sale
# Condition: 'New', 'Used', 'Parts'
# FK: ImageID

CREATE TABLE Item (
                ItemID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
                ImageID INTEGER,
                Title VARCHAR(60),
                Description VARCHAR(1000),
                ItemCondition VARCHAR(5) NOT NULL,
                PRIMARY KEY (ItemID),
                CONSTRAINT Image_Item_fk FOREIGN KEY (ImageID) REFERENCES Image (ImageID)
);


# AutoItem is a special type of item for automobiles

CREATE TABLE AutoItem (
                ItemID INTEGER NOT NULL,
                AutoVIN VARCHAR(50) NOT NULL,
                Mileage INTEGER NOT NULL,
                PRIMARY KEY (ItemID),
                CONSTRAINT Item_AutoItem_fk FOREIGN KEY (ItemID) REFERENCES Item (ItemID)
);


# AuctionUser is a bidder or Seller

CREATE TABLE AuctionUser (
#               UserID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
                UserID VARCHAR(20) NOT NULL,
#                DisplayName VARCHAR(20) NOT NULL,
                Password VARCHAR(20) NOT NULL,
                EMail VARCHAR(40) NOT NULL,
                Street VARCHAR(50) NOT NULL,
                CityState VARCHAR(50) NOT NULL,
                Zip VARCHAR(10) NOT NULL,
                PRIMARY KEY (UserID)
);


# Auction is the time-based sale of an item
# Status: 1 = Active, 2 = Completed, 3 = Cancelled
# FK: SellerID, ItemID

CREATE TABLE Auction (
                AuctionID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
                SellerID VARCHAR(20) NOT NULL,
                ItemID INTEGER NOT NULL,     
                CurrPrice REAL NOT NULL,
                Increment REAL NOT NULL,
                Status INTEGER NOT NULL,
                EndDate TIMESTAMP NOT NULL,
                Version INTEGER NOT NULL,
                PRIMARY KEY (AuctionID),
                CONSTRAINT AuctionUser_Auction_fk FOREIGN KEY (SellerID) REFERENCES AuctionUser (UserID),
                CONSTRAINT Item_Auction_fk FOREIGN KEY (ItemID) REFERENCES Item (ItemID)
);


# Watcher is any individual watching an auction
# FK: AuctionID

CREATE TABLE WatchedAuctions (
                WatcherID VARCHAR(20) NOT NULL,
                AuctionID INTEGER NOT NULL,
                CONSTRAINT Auction_Watcher_fk FOREIGN KEY (AuctionID) REFERENCES Auction (AuctionID),
			CONSTRAINT AuctionUser_Watcher_fk FOREIGN KEY (WatcherID) REFERENCES AuctionUser (UserID)
);


# Bid is a contract to purchase the item
# The highest bid wins
# FK: BidderID, AuctionID

CREATE TABLE Bid (
                BidID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
                BidderID VARCHAR(20) NOT NULL,
                AuctionID INTEGER NOT NULL,
                Amount REAL NOT NULL,
                BidTime TIMESTAMP NOT NULL,
                PRIMARY KEY (BidID),
                CONSTRAINT AuctionUser_Bid_fk FOREIGN KEY (BidderID) REFERENCES AuctionUser (UserID),
                CONSTRAINT Auction_Bid_fk FOREIGN KEY (AuctionID) REFERENCES Auction (AuctionID)
);