# JavaDB Database setup
# JDBC URL: jdbc:derby://localhost:1527/EmployeeDB
# User: oracle
# Password: welcome1
DROP TABLE EMPLOYEE;
DROP SEQUENCE EMP_ID_SEQ RESTRICT;

CREATE TABLE EMPLOYEE (
   	ID INTEGER, 
   	FIRSTNAME VARCHAR(40) NOT NULL, 
	LASTNAME VARCHAR(40) NOT NULL,
	BIRTHDATE DATE,
	SALARY REAL,
	PRIMARY KEY (ID)
);

CREATE SEQUENCE EMP_ID_SEQ
AS INTEGER
START WITH 1
INCREMENT BY 1;

# The sequence generates the primary key
#

INSERT INTO EMPLOYEE VALUES (NEXT VALUE FOR EMP_ID_SEQ, 'Troy', 'Hammer', '1965-03-31', 102109.15);
INSERT INTO EMPLOYEE VALUES (NEXT VALUE FOR EMP_ID_SEQ, 'Michael', 'Walton', '1986-08-25', 93400.20);
INSERT INTO EMPLOYEE VALUES (NEXT VALUE FOR EMP_ID_SEQ, 'Thomas', 'Fitzpatrick', '1961-09-22', 75123.45);
INSERT INTO EMPLOYEE VALUES (NEXT VALUE FOR EMP_ID_SEQ, 'Abhijit', 'Gopali', '1956-06-01', 89345.00);
INSERT INTO EMPLOYEE VALUES (NEXT VALUE FOR EMP_ID_SEQ, 'Rajiv', 'Sudahari', '1969-12-22', 68400.22);
INSERT INTO EMPLOYEE VALUES (NEXT VALUE FOR EMP_ID_SEQ, 'Patrice', 'Bergeron', '1970-09-18', 109345.00);